'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const ROOT=path.resolve(process.env.LINGQI_ROOT||path.join(__dirname,'..')),BASE=process.env.LINGQI_URL||'http://127.0.0.1:8787/';
const {chromium}=require(path.join(ROOT,'qa-tools/node_modules/playwright')),E=require(path.join(ROOT,'web/engine.js')),C=E.catalog;
const {readyJourneyFixture}=require('./story-fixtures.cjs');
const {stockRitualFixture,toTrial}=require('./ritual-fixtures.cjs');
const FILTER=process.env.LINGQI_FILTER||'';
const KEY='lingqi-save-v2',AGE='lingqi-age-confirmed',DIST=path.join(ROOT,'dist');
const report={filter:FILTER||null,partial:!!FILTER,startedAt:new Date().toISOString(),url:BASE,tests:[],pageErrors:[],consoleErrors:[],failedRequests:[],badResponses:[],externalRequests:[],screenshots:[],fixtureNotice:'Fresh-account tests have no state/resource injection. Later UI integration tests explicitly use a validated mid-game fixture; they do not establish economic reachability or full-game balance.'};
const ok=(x,m)=>assert.ok(x,m);let browser,fixturePage;
function observe(p){p.on('pageerror',e=>report.pageErrors.push(e.message));p.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});p.on('requestfailed',r=>report.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));p.on('response',r=>{if(r.status()>=400)report.badResponses.push({url:r.url(),status:r.status()});});p.on('request',r=>{if(!r.url().startsWith(BASE)&&!/^(data:|blob:)/.test(r.url()))report.externalRequests.push(r.url());});}
async function test(name,kind,fn){if(FILTER&&!name.includes(FILTER))return;const at=Date.now();try{const details=await fn();report.tests.push({name,kind,passed:true,durationMs:Date.now()-at,details});console.log('PASS '+name);}catch(e){report.tests.push({name,kind,passed:false,durationMs:Date.now()-at,error:e.stack||e.message});console.error('FAIL '+name+': '+e.message);if(fixturePage){try{await fixturePage.evaluate(()=>{const x=window.Lingqi.state();if(x?.battle)window.Lingqi.act('leaveBattle');if(x?.joint)window.Lingqi.act('jointCancel');});}catch(ignore){}}}}
async function make({width=390,fixture,native=false,fixedNow}={}){const context=await browser.newContext({viewport:{width,height:width>500?1000:844},isMobile:width<500,hasTouch:width<500,deviceScaleFactor:1,acceptDownloads:true});if(fixedNow!==undefined)await context.addInitScript(t=>{Date.now=()=>t;},fixedNow);if(fixture){const v=E.validate(fixture);ok(v.ok,'fixture validation '+v.error);await context.addInitScript(({key,age,fixture})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(fixture));localStorage.setItem(age,'yes');},{key:KEY,age:AGE,fixture:v.state});}if(native)await context.addInitScript(()=>{window.Native={persistSave:()=>true};});const page=await context.newPage();observe(page);await page.goto(BASE,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.Lingqi);return{context,page};}
const state=p=>p.evaluate(()=>window.Lingqi.state());
async function pager(p,scope,direction){const bs=p.locator(scope+' button');for(let i=0;i<await bs.count();i++){const b=bs.nth(i),label=(await b.getAttribute('aria-label'))||(await b.innerText()).trim();if(label===direction&&await b.isEnabled())return b;}return null;}
async function firstPage(p,scope){for(let guard=0;guard<100;guard++){const previous=await pager(p,scope,'上一页');if(!previous)return;await previous.click();}throw Error('Pagination did not reach first page');}
async function pagedControl(p,selector,predicate){async function find(){const scope=await p.locator('#modal-layer [role=dialog]').count()?'#modal-layer ':'';const bs=p.locator(scope+selector+':visible');for(let i=0;i<await bs.count();i++){const b=bs.nth(i),q=await b.evaluate(n=>JSON.parse(n.dataset.payload||'{}'));if(predicate(q)&&await b.isEnabled())return{b,q};}return null;}let hit=await find();if(hit)return hit;if(!await p.locator('#modal-layer [role="dialog"]').count())return null;await firstPage(p,'#modal-layer');for(let guard=0;guard<100;guard++){hit=await find();if(hit)return hit;const next=await pager(p,'#modal-layer','下一页');if(!next)return null;await next.click();}throw Error('Pagination did not find '+selector);}
async function action(p,type,predicate=()=>true){const shopTabs=p.locator('#modal-layer button[data-ui="shop-tab"]');if(await shopTabs.count()&&['buyJade','drawWithJade','exchangeJade'].includes(type)){const tab=type==='buyJade'?'jade':'exchange';for(let i=0;i<await shopTabs.count();i++){const b=shopTabs.nth(i);if((await b.evaluate(n=>JSON.parse(n.dataset.payload||'{}'))).tab===tab){await b.click();break;}}}const hit=await pagedControl(p,'button[data-action="'+type+'"]',predicate);if(!hit)throw Error('No enabled '+type);await hit.b.click();return hit.q;}
async function ui(p,id,predicate=()=>true){const hit=await pagedControl(p,'button[data-ui="'+id+'"]',predicate);if(!hit)throw Error('No UI '+id);await hit.b.click();return hit.q;}
async function catalogIds(p,scope,selector){await firstPage(p,scope);const ids=new Set;for(let guard=0;guard<100;guard++){const current=await p.locator(scope+' '+selector).evaluateAll(bs=>bs.map(b=>JSON.parse(b.dataset.payload||'{}').id||b.dataset.recipe));ok(current.every(id=>typeof id==='string'),'catalog entries expose stable IDs');for(const id of current)ids.add(id);const next=await pager(p,scope,'下一页');if(!next)return[...ids].sort();await next.click();}throw Error('Catalog pagination did not finish');}
async function chooseDungeon(p,id){await firstPage(p,'#page-content');for(let guard=0;guard<100;guard++){const bs=p.locator('#page-content button[data-ui="dungeon"]');for(let i=0;i<await bs.count();i++){const b=bs.nth(i),q=await b.evaluate(n=>JSON.parse(n.dataset.payload||'{}'));if(q.id===id){await b.click();return;}}const next=await pager(p,'#page-content','下一页');if(!next)throw Error('Dungeon missing from actual paged UI: '+id);await next.click();}throw Error('Dungeon pagination did not finish');}
async function pickLoadout(p,kind,index,id){await p.locator('#modal-layer [data-selection="category"][data-selection-value="'+kind+'"]').click();if(kind!=='heart')await p.locator('#modal-layer [data-selection="slot"][data-selection-value="'+index+'"]').click();for(let guard=0;guard<100;guard++){const option=p.locator('#modal-layer [data-selection="pick"][data-selection-value="'+id+'"]');if(await option.count()){ok(await option.isEnabled(),id+' icon available');await option.click();return;}const next=await pager(p,'#modal-layer','下一页');if(!next)throw Error('Loadout picker missing '+id);await next.click();}throw Error('Loadout pagination did not finish');}
async function returnActivity(p,type){const result=p.locator('[data-activity-settlement="'+type+'"]');ok(await result.isVisible(),'saved '+type+' reward screen');await ui(p,'activity-return');ok(await p.locator('.activity-settlement').count()===0,'return dismisses production result');}
async function close(p){const m=p.locator('#modal-layer [role="dialog"]');if(await p.locator('.activity-settlement').count()){await ui(p,'activity-return');ok(await p.locator('.activity-settlement').count()===0,'return dismisses production result before closing its source');}if(await m.isVisible()){await p.keyboard.press('Escape');ok(!await m.isVisible(),'modal close');}}
async function nav(p,id){await close(p);await p.locator('.nav-bottom button[data-page="'+id+'"]').click();await p.evaluate(()=>{document.getElementById('page-content').scrollTop=0;window.scrollTo({top:0,behavior:'instant'});});ok((await p.locator('#page-content').innerText()).length>15,id+' rendered');}
async function overflow(p){const w=await p.evaluate(()=>({viewport:innerWidth,html:document.documentElement.scrollWidth,body:document.body.scrollWidth}));ok(w.html<=w.viewport+1&&w.body<=w.viewport+1,'horizontal overflow '+JSON.stringify(w));return w;}
async function shot(p,name){await p.waitForTimeout(name.includes('summon')?800:240);const m=p.locator('#modal-layer .modal');if(await m.isVisible())await p.waitForFunction(()=>{const n=document.querySelector('#modal-layer .modal');return n&&Number(getComputedStyle(n).opacity)>.99;},null,{timeout:3000});await p.evaluate(()=>{document.getElementById('page-content').scrollTop=0;window.scrollTo({top:0,behavior:'instant'});const t=document.getElementById('toast');if(t)t.hidden=true;});await p.screenshot({path:path.join(DIST,name),fullPage:false});report.screenshots.push(name);}
function fixture(){const s=E.createState(Date.now());s.paths.magic={realm:1,layer:7,xp:100,reserve:0};s.paths.body={realm:0,layer:1,xp:0,reserve:0};s.training=false;s.stones=200000;s.tickets=200;s.materials={...s.materials,herb:3000,ore:3000,lotus:1000,insight:3000,essence:1000,crystal1:1000};s.progress.dungeonWins.resource_herb=1;s.stats.manualWins=5;for(const id of Object.keys(C.techniques)){const t=C.techniques[id];if(t.realm<=1)s.techniques[id]={level:5,branch:0,spent:0};}for(const id of ['heal0','shield0','purify0'])s.pills[id]=10;s.companions.yueheng.affinity=60;s.gacha.redPity=79;readyJourneyFixture(s,'chapter_0','protect',Date.now());return s;}
async function start(p,id){await p.evaluate(id=>window.Lingqi.showModal('dungeon',{id}),id);await action(p,'startDungeon',q=>q.id===id);const s=await state(p);ok(s.battle||s.exploration,'started '+id);return s;}
async function api(p,type,params={}){return p.evaluate(({type,params})=>window.Lingqi.act(type,params),{type,params});}
async function restore(p,s){s.lastAt=Date.now();ok(await p.evaluate(raw=>window.Lingqi.import(raw),JSON.stringify(s)),'fixture imported');await close(p);}
(async()=>{
 fs.mkdirSync(DIST,{recursive:true});
 browser=await chromium.launch({headless:true,ignoreDefaultArgs:['--disable-dev-shm-usage'],executablePath:process.env.LINGQI_CHROMIUM||path.join(ROOT,'qa-tools/browsers/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell'),args:['--no-sandbox','--disable-gpu'],env:{...process.env,FONTCONFIG_FILE:path.join(ROOT,'qa-tools/fonts.conf')}});
 report.browser=await browser.version();
 const fresh=await make(),p=fresh.page;
 await test('fresh: age confirmation, one-layer start and initial assets','fresh',async()=>{ok(await p.locator('#accept-age').isVisible(),'age visible');await ui(p,'enter');ok((await state(p))===null,'unchecked cannot enter');await p.locator('#accept-age').check();await ui(p,'enter');ok((await state(p)).paths.magic.layer===1,'numeric first layer');ok((await p.locator('#page-content').innerText()).includes('炼气一层'),'one-layer UI');await nav(p,'heaven');await ui(p,'gacha-pool');const lockedPool=await p.locator('#modal-layer').innerText();ok(lockedPool.includes('第二境'),'unopened pool explains unlock');ok(!/Infinity|NaN/.test(lockedPool),'unopened pool has no invalid probability');await close(p);await nav(p,'cultivation');await overflow(p);return{startStones:(await state(p)).stones};});
 await test('fresh: freely chosen resource dungeon starts, pauses, resumes and wins','fresh',async()=>{await nav(p,'adventure');await ui(p,'dungeon',q=>q.id==='resource_herb');await action(p,'startDungeon');ok((await state(p)).battle,'new-account resource battle started');ok(await p.locator('.monster-portrait').count()>0,'ordinary monster sprites render');await action(p,'pauseBattle',q=>q.paused===true);const before=await state(p);await p.waitForTimeout(1100);const after=await state(p);ok(after.battle.time===before.battle.time,'pause freezes battle time');await action(p,'pauseBattle',q=>q.paused===false);await p.waitForFunction(()=>!window.Lingqi.state().battle,null,{timeout:70000});const s=await state(p);ok(s.lastBattleResult?.win||s.lastBattleResult?.victory,'new-account victory');ok(s.stats.manualWins===1,'one real victory');ok(Array.isArray(s.battleReports)&&s.battleReports.length===1,'one actual report in persistent history');ok(s.progress.dungeonWins.resource_herb>=1,'resource win recorded');await close(p);await p.evaluate(()=>window.Lingqi.showModal('battle-history'));ok((await p.locator('#modal-layer').innerText()).includes('青岚灵圃'),'actual first victory in battle history');await ui(p,'battle-report');ok((await p.locator('#modal-layer').innerText()).includes('挑战胜利'),'selected history report shows win');await close(p);return{time:s.lastBattleResult.time,stones:s.stones,wins:s.stats.manualWins,rewards:s.lastBattleResult.rewards};});
 await test('fresh: earned or crafted XP advances exactly one small layer','fresh',async()=>{await close(p);await nav(p,'cultivation');let s=await state(p);if(s.paths.magic.xp<E.modules.core.xpNeeded(s)){await p.evaluate(()=>window.Lingqi.showModal('alchemy'));await action(p,'craftPill',x=>x.id==='qi0');await returnActivity(p,'craftPill');await action(p,'usePill',x=>x.id==='qi0');await close(p);}await action(p,'levelUp');s=await state(p);ok(s.paths.magic.realm===0&&s.paths.magic.layer===2,'numeric one-to-two progression');ok((await p.locator('#page-content').innerText()).includes('炼气二层'),'second-layer displayed');return{realm:s.paths.magic.realm,layer:s.paths.magic.layer,stones:s.stones};});
 await test('fresh: current account persists across reload','fresh',async()=>{await close(p);const before=await state(p);await p.reload({waitUntil:'networkidle'});const after=await state(p);ok(after.stats.manualWins===before.stats.manualWins&&after.progress.dungeonWins.resource_herb===before.progress.dungeonWins.resource_herb,'victory persisted');assert.deepEqual(after.battleReports,before.battleReports,'history persists across reload');});
 await fresh.context.close();
 const seed=fixture(),sys=await make({fixture:seed}),q=sys.page;fixturePage=q;
 await test('fixture: six pages and mobile dialogs render without overflow','fixture',async()=>{for(const id of ['cultivation','character','adventure','cave','fate','heaven']){await nav(q,id);await overflow(q);}for(const id of ['techniques','loadout','equipment','alchemy','treasures','settings','help','gacha-odds','gacha-pool','gacha-history','battle-settings']){await q.evaluate(id=>window.Lingqi.showModal(id),id);ok(await q.locator('#modal-layer [role="dialog"]').isVisible(),id);await overflow(q);await close(q);}});
 await test('fixture: 48 techniques and school/type filter plus source link','fixture',async()=>{await q.evaluate(()=>window.Lingqi.showModal('techniques'));assert.deepEqual(await catalogIds(q,'#modal-layer','button[data-action="upgradeTechnique"], #modal-layer button[data-action="learnTechnique"]'),Object.keys(C.techniques).sort(),'48 actual catalog entries across all pages');await q.locator('#filter-tech-school').selectOption('sword');assert.deepEqual(await catalogIds(q,'#modal-layer','button[data-action="upgradeTechnique"], #modal-layer button[data-action="learnTechnique"]'),Object.values(C.techniques).filter(t=>t.school==='sword').map(t=>t.id).sort(),'8 sword entries across all pages');await q.locator('#filter-tech-kind').selectOption('skill');assert.deepEqual(await catalogIds(q,'#modal-layer','button[data-action="upgradeTechnique"], #modal-layer button[data-action="learnTechnique"]'),Object.values(C.techniques).filter(t=>t.school==='sword'&&t.kind==='skill').map(t=>t.id).sort(),'4 sword skills');ok(await q.locator('#modal-layer button[data-ui="source"]').count()>0,'source navigation');await ui(q,'source');ok(await q.locator('#modal-layer [role="dialog"]').isVisible(),'source dungeon opened');await close(q);});
 await test('fixture: 18 alchemy recipes; crafting and qi use','fixture',async()=>{await q.evaluate(()=>window.Lingqi.showModal('alchemy'));assert.deepEqual(await catalogIds(q,'#modal-layer','article.recipe-card'),Object.keys(C.recipes).sort(),'18 recipes across all pages');const before=await state(q);await action(q,'craftPill',x=>x.id==='qi0');const made=await state(q);ok(made.pills.qi0>before.pills.qi0,'pill crafted');ok(made.stones<before.stones&&made.materials.herb<before.materials.herb,'cost paid');await returnActivity(q,'craftPill');await action(q,'usePill',x=>x.id==='qi0');const after=await state(q);ok(after.pills.qi0===made.pills.qi0-1&&after.paths.magic.xp>made.paths.magic.xp,'pill consumed for XP');await close(q);});
 await test('fixture: red forging, six slots, protection and enhancement','fixture',async()=>{const f=await state(q);f.blueprints=Object.keys(C.sets);await restore(q,f);await q.evaluate(()=>window.Lingqi.showModal('forge'));await q.locator('#forge-rarity').selectOption('5');await q.locator('#forge-slot').selectOption('weapon');await q.locator('#forge-set').selectOption('thunder');await action(q,'forgeGear');const made=await state(q),g=made.bag.find(g=>g.rarity===5);ok(g,'red equipment created');await close(q);await q.evaluate(()=>window.Lingqi.showModal('equipment'));ok(await q.locator('#modal-layer .rarity-5').count()>0,'red rarity UI');ok(Object.keys(made.equipped).length===6,'six slots');const r=await api(q,'equipGear',{uid:g.uid});ok(r.ok,r.message);ok((await api(q,'enhanceSlot',{slot:'weapon'})).ok,'slot enhancement');ok(!(await api(q,'recycleGear',{uid:g.uid})).ok,'equipped red protected');await close(q);return{red:g.uid};});
 await test('fixture: loadout selects skills and presets retain configuration','fixture',async()=>{await q.evaluate(()=>window.Lingqi.showModal('loadout'));await q.locator('#modal-layer [data-selection="category"][data-selection-value="skill"]').click();for(let i=0;i<4;i++){await q.locator('#modal-layer [data-selection="slot"][data-selection-value="'+i+'"]').click();await q.locator('#modal-layer [data-selection="clear"]').click();}await pickLoadout(q,'heart',0,'thunder_heart_0');const skills=['thunder_skill_0','array_skill_0','body_skill_1','thunder_skill_1'];for(let i=0;i<4;i++)await pickLoadout(q,'skill',i,skills[i]);await action(q,'setLoadout');assert.deepEqual((await state(q)).loadouts.magic.skills,skills);ok((await api(q,'savePreset',{index:0})).ok,'save preset');ok((await api(q,'loadPreset',{index:0})).ok,'load preset');});
 await test('fixture: gacha probabilities, target selection, hard red and reload','fixture',async()=>{await nav(q,'heaven');await ui(q,'gacha-odds');ok((await q.locator('#modal-layer').innerText()).includes('第80次必红'),'80 hard rule');ok(await q.locator('#modal-layer table tr').count()===7,'joint table and total');await close(q);await ui(q,'gacha-target');const options=await q.locator('#gacha-target option').evaluateAll(ns=>ns.map(x=>x.value).filter(Boolean));ok(options.length>0,'legal targets');await q.locator('#gacha-target').selectOption(options[0]);await action(q,'setGachaTarget');const before=await state(q);await action(q,'draw',x=>x.count===1);const drawn=await state(q);ok(drawn.tickets===before.tickets-1&&drawn.dust===before.dust+2,'atomic draw costs');ok(drawn.gacha.redPity===0,'hard red resets');ok(drawn.gacha.history.at(-1).rarity===5,'80th draw red');ok(await q.locator('#modal-layer .rarity-5').count()>0,'red draw visible');await close(q);await action(q,'draw',x=>x.count===10);const ten=await state(q);ok(ten.tickets===drawn.tickets-10&&ten.gacha.total===drawn.gacha.total+10,'ten draw commits ten');await close(q);await q.reload({waitUntil:'networkidle'});const after=await state(q);assert.deepEqual(after.gacha,ten.gacha,'gacha state survives reload');return{target:before.gacha.target,total:after.gacha.total};});

 await test('fixture: simulated jade shop direct credit exchange reload and failed-save rollback','fixture',async()=>{
  const baseline=await state(q);try{
   await nav(q,'heaven');await ui(q,'shop');await action(q,'buyJade',x=>x.packageId==='p68');
   const purchased=await state(q);ok(purchased.jade===baseline.jade+780,'listed jade credited');ok(purchased.shop.purchases===baseline.shop.purchases+1,'receipt stored');
   await action(q,'exchangeJade',x=>x.count===10);const converted=await state(q);ok(converted.jade===purchased.jade-600,'conversion charged exactly');ok(converted.tickets===purchased.tickets+10,'ten tickets credited');
   await shot(q,'v3-mobile-shop.png');await q.reload({waitUntil:'networkidle'});await q.waitForFunction(()=>window.Lingqi?.state);
   const restored=await state(q);ok(restored.jade===converted.jade&&restored.shop.purchases===converted.shop.purchases,'shop survives reload');
   await nav(q,'heaven');await ui(q,'shop');await q.evaluate(()=>{window.Native={persistSave:()=>false};});
   const failed=await api(q,'buyJade',{packageId:'p648'});ok(!failed.ok,'native failed purchase rejected');const after=await state(q);ok(after.jade===restored.jade&&after.shop.purchases===restored.shop.purchases,'no uncommitted currency or receipt');
   await q.evaluate(()=>delete window.Native);
  }finally{await q.evaluate(()=>delete window.Native);await restore(q,baseline);}
 });
 await test('fixture: animated jade ten-pull skip and mid-animation reload preserve prizes and pity','fixture',async()=>{
  const baseline=await state(q);try{
   await nav(q,'heaven');await ui(q,'shop');await action(q,'buyJade',x=>x.packageId==='p648');const before=await state(q);
   await action(q,'drawWithJade',x=>x.count===10);ok(await q.locator('[data-animation="summoning"]').isVisible(),'altar phase is visible');ok(await q.locator('.ritual-orbit').count()===2,'formation rings rendered');
   await shot(q,'v3-mobile-summon.png');await ui(q,'summon-skip');ok(await q.locator('.reward-card').count()===10,'all ten prizes revealed');await shot(q,'v3-mobile-draw.png');
   const ten=await state(q);ok(ten.jade===before.jade-600&&ten.tickets===before.tickets,'jade cost preserves ordinary tickets');ok(ten.gacha.total===before.gacha.total+10,'ten draws committed exactly once');
   await close(q);await ui(q,'shop');await action(q,'drawWithJade',x=>x.count===1);await q.waitForSelector('.animated-reveal',{timeout:50000});ok(await q.locator('.reward-card').count()===1,'natural animation leads to one card');
   const single=await state(q);await close(q);await ui(q,'shop');await action(q,'drawWithJade',x=>x.count===1);ok(await q.locator('[data-animation="summoning"]').isVisible(),'second altar begins');
   const pending=await state(q);await q.reload({waitUntil:'networkidle'});await q.waitForFunction(()=>window.Lingqi?.state);const loaded=await state(q);
   ok(loaded.gacha.total===pending.gacha.total&&loaded.jade===pending.jade,'reload never redraws or refunds');ok(loaded.gacha.history.length===pending.gacha.history.length&&loaded.gacha.redPity===pending.gacha.redPity,'history and pity retained');
   ok(loaded.gacha.total===single.gacha.total+1,'single frame reward committed once');
  }finally{await restore(q,baseline);}
 });
 await test('fixture: six dungeon families selectable and all can begin','fixture',async()=>{const baseline=await state(q);for(const [type,id] of [['resource','resource_ore'],['sect','sect_thunder_0'],['boss','boss_2'],['tower','tower'],['cave','cave_0'],['trial','trial']]){const f=JSON.parse(JSON.stringify(baseline));if(type==='sect')f.sect={...f.sect,joined:true,school:'thunder'};if(type==='trial'){f.paths.magic.layer=10;f.paths.magic.xp=E.modules.core.xpNeeded(f);stockRitualFixture(f);toTrial(f,Date.now());}await restore(q,f);await nav(q,'adventure');await ui(q,'dungeon-type',x=>x.id===type);assert.deepEqual(await catalogIds(q,'#page-content','button[data-ui="dungeon"]'),Object.values(C.dungeons).filter(d=>d.type===type).map(d=>d.id).sort(),type+' complete paged catalog');await chooseDungeon(q,id);await action(q,'startDungeon',x=>x.id===id);if(type==='cave'){const s=await state(q);ok(s.exploration.choices.length>0,'cave route choices');ok((await api(q,'finishCave')).ok,'cave may exit');}else{ok((await api(q,'pauseBattle',{paused:true})).ok,'can pause');ok((await api(q,'leaveBattle')).ok,'can leave');}}await restore(q,baseline);});
 await test('fixture: manual skill, target, tactical pause and battle reload','fixture',async()=>{const baseline=await state(q);await start(q,'boss_2');await api(q,'setBattleAuto',{enabled:false});await api(q,'pauseBattle',{paused:true});const before=await state(q);await q.waitForTimeout(700);ok((await state(q)).battle.time===before.battle.time,'pause freezes');await q.reload({waitUntil:'networkidle'});const reloaded=await state(q);ok(reloaded.battle&&reloaded.battle.paused,'reload preserves paused fight');assert.deepEqual(reloaded.battle.enemies.map(x=>x.hp),before.battle.enemies.map(x=>x.hp),'enemy HP preserved');const count=reloaded.battle.enemies.length;ok((await api(q,'targetEnemy',{index:count>1?1:0})).ok,'target selection');await action(q,'pauseBattle',x=>x.paused===false);await q.waitForFunction(()=>Array.from(document.querySelectorAll('button[data-action="useSkill"]')).some(b=>!b.disabled&&JSON.parse(b.dataset.payload).id.startsWith('thunder')),null,{timeout:18000});await action(q,'useSkill',x=>x.id.startsWith('thunder'));ok((await state(q)).stats.skillCasts>baseline.stats.skillCasts,'manual skill counted');await api(q,'pauseBattle',{paused:true});await shot(q,'v3-mobile-battle.png');await api(q,'leaveBattle');await restore(q,baseline);});
 await test('fixture: story choice and sect action persist','fixture',async()=>{await nav(q,'fate');await ui(q,'story-open',x=>x.episode==='chapter_0');const before=await state(q);await action(q,'claimChapter',x=>x.choice==='protect');const after=await state(q);ok(after.story.chapter===before.story.chapter+1&&after.story.mercy===before.story.mercy+1,'story advances');await returnActivity(q,'claimChapter');if(await q.locator('[data-narrative=story]').count())await ui(q,'story-exit');await ui(q,'fate-tab',x=>x.id==='sect');if(!(await state(q)).sect.joined){await action(q,'joinSect',x=>x.school==='thunder');}ok((await state(q)).sect.joined,'sect joined');if(!(await state(q)).learnedRecipes.includes('qi1')){const learned=await api(q,'researchRecipe',{id:'qi1'});ok(learned.ok,'research current-tier commission recipe '+learned.message);}for(let i=0;i<5;i++){const crafted=await api(q,'craftPill',{id:'qi1',count:1,control:0});ok(crafted.ok,'actual post-join crafting '+crafted.message);await returnActivity(q,'craftPill');}await close(q);await action(q,'claimCommission',x=>x.id==='alchemy');ok((await state(q)).sect.contribution>0,'earned contribution');});
 await test('fixture: adult companion bond and complete joint session with reload','fixture',async()=>{await nav(q,'fate');await ui(q,'fate-tab',x=>x.id==='companions');await action(q,'talk',x=>x.companion==='yueheng');ok(await q.locator('.conversation-portrait').isVisible(),'relationship conversation and expression rendered');await shot(q,'v3-mobile-conversation.png');await close(q);await action(q,'bond',x=>x.companion==='yueheng');await ui(q,'joint-invite',x=>x.companion==='yueheng');await action(q,'jointInvite');const begin=await state(q);ok(begin.joint,'joint started');for(let i=0;i<3;i++){const s=await state(q);const rhythm=s.joint.rhythm||s.joint.rhythms;await action(q,'jointStep',x=>x.choice===rhythm[s.joint.round]);if(i===0){const partial=(await state(q)).joint;await q.reload({waitUntil:'networkidle'});assert.deepEqual((await state(q)).joint,partial,'joint reload preserved');await q.evaluate(()=>window.Lingqi.showModal('joint'));}}const end=await state(q);ok(!end.joint&&end.stats.joints===begin.stats.joints+1,'three rounds completed once');});
 await test('fixture: export download, valid import and invalid-import protection','fixture',async()=>{await q.evaluate(()=>window.Lingqi.showModal('settings'));const pending=q.waitForEvent('download');await ui(q,'export-save');const d=await pending,file=await d.path();const raw=fs.readFileSync(file,'utf8');ok(E.validate(raw).ok,'download contains valid save');await close(q);const before=await state(q);ok(!(await q.evaluate(()=>window.Lingqi.import('{"version":3}'))),'invalid save rejected');assert.deepEqual((await state(q)).bag,before.bag,'invalid import preserves assets');await q.evaluate(()=>window.Lingqi.showModal('settings'));const picker=q.waitForEvent('filechooser');await ui(q,'import-save');const chooser=await picker,imported=JSON.parse(raw);imported.player.name='导入验证者';await chooser.setFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await q.waitForFunction(()=>window.Lingqi.state().player.name==='导入验证者',null,{timeout:5000});assert.deepEqual((await state(q)).bag,imported.bag,'file chooser import preserves equipment');ok((await api(q,'rename',{name:before.player.name})).ok,'restore player name after import check');await close(q);});
 await test('fixture: Native persistence failure rolls back reward and RNG','fixture',async()=>{await close(q);await q.evaluate(()=>{window.Native={persistSave:()=>false};});const before=await state(q);const r=await api(q,'draw',{count:1});ok(!r.ok,'failed native commit rejected');const after=await state(q);assert.deepEqual(after.gacha,before.gacha,'pity/history rolled back');assert.deepEqual(after.rngStreams,before.rngStreams,'RNG rolled back');ok(after.tickets===before.tickets&&after.dust===before.dust,'spend/reward rolled back');await q.evaluate(()=>{delete window.Native;});ok(await q.evaluate(()=>window.Lingqi.save()),'storage restored');});
await test('fixture: both cultivation routes preserve progress and unlock auto-small by highest path','fixture',async()=>{const baseline=await state(q);await nav(q,'cultivation');await action(q,'switchRoute',x=>x.route==='body');const body=await state(q);ok(body.route==='body'&&body.paths.body.layer===1,'low-stage body selected');assert.deepEqual(body.paths.magic,baseline.paths.magic,'magic progress retained');const toggle=q.locator('button[data-action="setAutoSmall"]');ok(await toggle.isEnabled(),'highest route unlocks auto-small button');await toggle.click();ok((await state(q)).autoSmall,'auto-small action accepted on lower route');await action(q,'switchRoute',x=>x.route==='magic');const back=await state(q);assert.deepEqual(back.paths,baseline.paths,'both paths retained');assert.deepEqual(back.gacha,baseline.gacha,'switching never resets gacha');await restore(q,baseline);});

 await test('fixture: completed trial permits one major breakthrough and preserves route','fixture',async()=>{const baseline=await state(q),f=JSON.parse(JSON.stringify(baseline));f.paths.magic.layer=10;f.paths.magic.xp=E.modules.core.xpNeeded(f);f.paths.magic.reserve=0;f.progress.trialWins['magic:1']=true;delete f.ritualLegacyWins;delete f.ritual;delete f.ritualHistory;await restore(q,f);await nav(q,'cultivation');await ui(q,'ritual-open');await action(q,'breakthrough');const next=await state(q);ok(next.paths.magic.realm===2&&next.paths.magic.layer===1,'one major boundary reached');assert.deepEqual(next.paths.body,f.paths.body,'other route preserved');ok((await q.locator('#modal-layer').innerText()).includes('金丹'),'new realm confirmation UI');await ui(q,'ritual-exit');ok((await q.locator('#page-content').innerText()).includes('金丹一层'),'new realm one-layer cultivation UI');await restore(q,baseline);});
await test('fixture: passive XP unlocks advancement button without navigation','fixture',async()=>{const f=E.createState(Date.now());f.paths.magic.xp=95;const x=await make({fixture:f});const b=x.page.locator('button[data-action="levelUp"]');ok(await b.isDisabled(),'initially below threshold');await x.page.waitForFunction(()=>window.Lingqi.state().paths.magic.xp>=100,null,{timeout:12000});await x.page.waitForFunction(()=>!document.querySelector('button[data-action="levelUp"]').disabled,null,{timeout:3000});await b.click();ok((await state(x.page)).paths.magic.layer===2,'passive-earned threshold can advance');await x.context.close();});

await test('fixture: two-hour offline summary agrees with HUD and never clears challenges','fixture',async()=>{const f=E.createState(Date.now()-7200000);const x=await make({fixture:f}),p=x.page;ok(await p.locator('#modal-layer [role="dialog"]').isVisible(),'offline summary opened');const text=await p.locator('#modal-layer').innerText();ok(text.includes('归来')&&text.includes('2 小时'),'two-hour summary '+text);const settled=await state(p);ok(settled.stones>f.stones&&settled.paths.magic.xp+settled.paths.magic.reserve>0,'passive rewards granted');ok(settled.paths.magic.realm===0&&settled.paths.magic.layer===1&&settled.stats.manualWins===0&&settled.progress.firstClears.length===0,'passive never advances major content');ok(await p.locator('#hud-stones').innerText()===Number(settled.stones).toLocaleString('zh-CN',{maximumFractionDigits:1}),'HUD agrees with settled state');await close(p);await p.reload({waitUntil:'networkidle'});const reloaded=await state(p);ok(reloaded.stones<settled.stones+100,'no second two-hour settlement');await x.context.close();});
 await test('fixture: 360 px HUD handles large inventories without horizontal overflow','fixture',async()=>{const f=fixture();f.stones=1e10;f.tickets=1e10;f.dust=1e10;const x=await make({fixture:f,width:360});await overflow(x.page);await nav(x.page,'heaven');await overflow(x.page);await x.context.close();});

 await test('fixture: alchemy UI queue, three fire rounds, reload, reward once and storage rollback','fixture',async()=>{
  const now=Date.now(),f=fixture();f.lastAt=now;const x=await make({fixture:f,fixedNow:now}),p=x.page;
  try{
   await p.evaluate(()=>window.Lingqi.showModal('alchemy'));await firstPage(p,'#modal-layer');await p.locator('#pill-count').selectOption('3');
   const before=await state(p);await action(p,'queuePill',q=>q.id==='heal0');let s=await state(p),j=s.alchemy.jobs[0];ok(j&&j.count===3&&j.status==='queued','three queued');ok(s.pills.heal0===before.pills.heal0,'queue does not grant pills');ok(s.stones===before.stones-j.cost.stones,'base stones prepaid');for(const [k,v] of Object.entries(j.cost.materials||{}))ok(s.materials[k]===before.materials[k]-v,'prepaid '+k);
   await action(p,'startAlchemyControl',q=>q.jobId===j.id);s=await state(p);j=s.alchemy.jobs[0];ok(j.status==='control'&&j.round===0,'control started');ok(s.stones===before.stones-j.cost.stones-j.controlCost.stones,'control fee paid separately');ok(!(await api(p,'finishAlchemyJob',{jobId:j.id})).ok,'unfinished control cannot claim');
   await action(p,'stokeAlchemy',q=>q.jobId===j.id&&q.fire===j.rhythm[j.round]);const partial=(await state(p)).alchemy;await p.reload({waitUntil:'networkidle'});assert.deepEqual((await state(p)).alchemy,partial,'mid-control reload retains exact job');await p.evaluate(()=>window.Lingqi.showModal('alchemy'));await shot(p,'v3-mobile-alchemy.png');
   const snapshot=await state(p);await p.evaluate(()=>{window.Native={persistSave:()=>false};});try{j=snapshot.alchemy.jobs[0];const bad=await api(p,'stokeAlchemy',{jobId:j.id,fire:j.rhythm[j.round]});ok(!bad.ok,'failed native fire step rejected');assert.deepEqual((await state(p)).alchemy,snapshot.alchemy,'fire choices/score/round rolled back');ok((await state(p)).stones===snapshot.stones,'stored fees rolled back');}finally{await p.evaluate(()=>{delete window.Native;});}
   for(let i=0;i<2;i++){j=(await state(p)).alchemy.jobs[0];await action(p,'stokeAlchemy',q=>q.jobId===j.id&&q.fire===j.rhythm[j.round]);}
   s=await state(p);j=s.alchemy.jobs[0];ok(j.status==='ready'&&j.round===3&&j.score===3&&j.bonus>0,'three correct rounds ready bonus');ok(s.pills.heal0===before.pills.heal0,'ready is not automatic payout');await action(p,'finishAlchemyJob',q=>q.jobId===j.id);const done=await state(p);ok(done.alchemy.jobs.length===0&&done.pills.heal0===before.pills.heal0+j.count+j.bonus,'pills claimed exactly once');ok(!(await api(p,'finishAlchemyJob',{jobId:j.id})).ok,'duplicate claim rejected');
   const failBase=await state(p);await p.evaluate(()=>{window.Native={persistSave:()=>false};});try{ok(!(await api(p,'queuePill',{id:'heal0',count:1})).ok,'failed queue rejected');const reverted=await state(p);assert.deepEqual(reverted.alchemy,failBase.alchemy,'queue and nonce rolled back');assert.deepEqual(reverted.rngStreams,failBase.rngStreams,'queue rhythm RNG rolled back');assert.deepEqual(reverted.materials,failBase.materials,'queue materials rolled back');ok(reverted.stones===failBase.stones,'queue stones rolled back');}finally{await p.evaluate(()=>{delete window.Native;});}
   return{baseCount:j.count,bonus:j.bonus,rounds:j.round};
  }finally{await x.context.close();}
 });
 await test('fixture: alchemy capacity, ordinary payout and cancellation refund','fixture',async()=>{
  const now=Date.now(),f=fixture();f.lastAt=now;const x=await make({fixture:f,fixedNow:now}),p=x.page;
  try{
   const before=await state(p),capacity=await p.evaluate(()=>window.WendaoEconomy.alchemyView(window.Lingqi.state()).capacity);for(let i=0;i<capacity;i++)ok((await api(p,'queuePill',{id:'heal0',count:1})).ok,'fill slot '+i);const full=await state(p);ok(!(await api(p,'queuePill',{id:'heal0',count:1})).ok,'full queue rejects');assert.deepEqual((await state(p)).alchemy,full.alchemy,'rejection retains all jobs');ok((await state(p)).stones===full.stones,'full rejection spends nothing');
   await p.evaluate(()=>window.Lingqi.showModal('alchemy'));const first=full.alchemy.jobs[0];await action(p,'finishAlchemyJob',q=>q.jobId===first.id);ok((await state(p)).pills.heal0===before.pills.heal0+1,'ordinary queue grants one base pill');await returnActivity(p,'finishAlchemyJob');
   const second=(await state(p)).alchemy.jobs[0];await action(p,'startAlchemyControl',q=>q.jobId===second.id);const paid=await state(p),job=paid.alchemy.jobs.find(j=>j.id===second.id);await ui(p,'confirm',q=>q.type==='cancelAlchemyJob'&&q.payload?.jobId===job.id);await action(p,'cancelAlchemyJob',q=>q.jobId===job.id);const cancelled=await state(p);ok(cancelled.stones===paid.stones+job.cost.stones+job.controlCost.stones,'base and control fees refunded');for(const [k,v] of Object.entries(job.cost.materials||{}))ok(cancelled.materials[k]===paid.materials[k]+v,'refund '+k);ok(cancelled.alchemy.jobs.length===capacity-2,'cancelled job removed');ok(cancelled.pills.heal0===before.pills.heal0+1,'cancel grants no pill');ok(!(await api(p,'cancelAlchemyJob',{jobId:job.id})).ok,'duplicate refund rejected');
   const nonces=cancelled.alchemy.nextId;ok((await api(p,'queuePill',{id:'heal0',count:1})).ok,'queue after cancel');const created=(await state(p)).alchemy.jobs.at(-1);ok(created.id==='a'+nonces,'nonce never reused');return{capacity};
  }finally{await x.context.close();}
 });

 await test('fixture: terminal trial links to final chapter, all three endings persist and no seventh realm','fixture',async()=>{
  for(const choice of ['guardian','wanderer','teacher']){
   const f=E.createState(Date.now());f.paths.magic.realm=5;f.paths.magic.layer=10;f.paths.magic.xp=E.modules.core.xpNeeded(f);f.training=false;f.progress.trialWins['magic:5']=true;f.progress.endingTrials.magic=true;f.progress.bossWins.boss_11=1;f.stats.manualWins=50;f.story.chapter=5;f.story.completed=[0,1,2,3,4];f.story.mercy=5;delete f.ritualLegacyWins;delete f.ritual;delete f.ritualHistory;readyJourneyFixture(f,'chapter_5','protect',Date.now());
   const x=await make({fixture:f}),p=x.page;try{await ui(p,'ritual-open');await ui(p,'ending-story');ok(await p.locator('button[data-page="fate"]').getAttribute('aria-current')==='page','terminal link navigates to fate');await ui(p,'story-open',q=>q.episode==='chapter_5');await action(p,'claimChapter',q=>q.choice==='protect');ok((await state(p)).story.chapter===6,'final chapter complete');await returnActivity(p,'claimChapter');if(await p.locator('[data-narrative=story]').count())await ui(p,'story-exit');await action(p,'ending',q=>q.choice===choice);const ended=await state(p);ok(ended.story.ending?.id===choice,'selected '+choice);ok(ended.paths.magic.realm===5&&ended.paths.magic.layer===10,'no seventh realm');await p.reload({waitUntil:'networkidle'});assert.deepEqual((await state(p)).story.ending,ended.story.ending,'ending persists '+choice);await nav(p,'fate');ok((await p.locator('#page-content').innerText()).includes(ended.story.ending.title),'ending story visible');}finally{await x.context.close();}
  }
 });

 await test('recovery: corrupt stored data retained and exportable without overwrite','recovery',async()=>{const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});const raw='{"version":3,"bogus":true}';await context.addInitScript(({raw,key,age})=>{localStorage.setItem(key,raw);localStorage.setItem(age,'yes');},{raw,key:KEY,age:AGE});const p=await context.newPage();observe(p);await p.goto(BASE,{waitUntil:'networkidle'});ok((await p.locator('#app').innerText()).includes('仙途恢复'),'recovery screen');ok(await p.evaluate(key=>localStorage.getItem(key),KEY)===raw,'corrupt original retained');const pending=p.waitForEvent('download');await ui(p,'export-recovery');const d=await pending;assert.equal(fs.readFileSync(await d.path(),'utf8'),raw,'exact recovery export');await context.close();});

 await test('fixture: collection pages screenshots and readable red UI','fixture',async()=>{await nav(q,'cultivation');await shot(q,'v3-mobile-home.png');await nav(q,'adventure');await ui(q,'dungeon-type',x=>x.id==='boss');await shot(q,'v3-mobile-dungeons.png');await nav(q,'cave');await shot(q,'v3-mobile-forge.png');await nav(q,'heaven');await shot(q,'v3-mobile-heaven.png');await nav(q,'fate');await ui(q,'fate-tab',x=>x.id==='companions');await shot(q,'v3-mobile-companions.png');});
 await sys.context.close();
 for(const width of [360,412,1440]){await test('responsive: '+width+' px six pages and probability dialog','fixture',async()=>{const x=await make({width,fixture:seed});for(const id of ['cultivation','character','adventure','cave','fate','heaven']){await nav(x.page,id);await overflow(x.page);}await x.page.evaluate(()=>window.Lingqi.showModal('gacha-odds'));await overflow(x.page);await close(x.page);await nav(x.page,'cultivation');if(width===1440)await shot(x.page,'v3-desktop-home.png');await x.context.close();});}
 await test('asset integrity: local resources and browser diagnostics','environment',async()=>{const files=['v3-world.png','v3-forge.png','v3-map-atlas-a.png','v3-map-atlas-b.png','v3-boss-atlas.png','v3-skills-atlas.png','v3-heroes.png','v3-items-atlas.png','v3-hero-expressions.png','v3-monster-atlas.png','v3-summon.png','v3-shop.png','v3-chapter-atlas.png','v3-cardback.png'];report.assetFiles=files.map(name=>({name,exists:fs.existsSync(path.join(ROOT,'web/assets',name))}));ok(report.assetFiles.every(x=>x.exists),'missing final asset '+JSON.stringify(report.assetFiles.filter(x=>!x.exists)));const ctx=await browser.newContext(),imgpage=await ctx.newPage();observe(imgpage);await imgpage.goto(BASE,{waitUntil:'networkidle'});report.decodedAssets=await imgpage.evaluate(async files=>Promise.all(files.map(name=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve({name,width:i.naturalWidth,height:i.naturalHeight});i.onerror=()=>reject(Error('Image decode failed '+name));i.src='assets/'+name;}))),files);ok(report.decodedAssets.every(x=>x.width>100&&x.height>100),'all atlases decode');await ctx.close();ok(report.pageErrors.length===0,'page errors '+JSON.stringify(report.pageErrors));ok(report.failedRequests.length===0,'failed requests '+JSON.stringify(report.failedRequests));ok(report.badResponses.length===0,'bad responses '+JSON.stringify(report.badResponses));ok(report.consoleErrors.length===0,'console errors '+JSON.stringify(report.consoleErrors));ok(report.externalRequests.length===0,'unexpected external requests');});
})().catch(e=>{report.fatal=e.stack||e.message;console.error(e);}).finally(async()=>{if(browser)await browser.close();report.finishedAt=new Date().toISOString();report.passed=!report.fatal&&report.tests.length>0&&report.tests.every(x=>x.passed);fs.writeFileSync(path.join(DIST,'browser-v3-report'+(FILTER?'-'+FILTER.replace(/[^a-zA-Z0-9_-]/g,'_'):'')+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,tests:report.tests.length,failed:report.tests.filter(x=>!x.passed).map(x=>x.name),pageErrors:report.pageErrors,badResponses:report.badResponses.length,screenshots:report.screenshots}));if(!report.passed)process.exitCode=1;});
